### ISSUE TITLE
Code Organisation - index.js

### ISSUE THREAD

**Issue by EngineeringErgonomics** [marvy896/Calculator#3]
Looking at your code, you have placed all your methods in the same class "Calculator". However, some of these methods are not necessarily specific to a calculator app and, when part of a larger system, other apps may want to use that functionality.

How could you better organise your classes?

I notice at the bottom of the file you have a series of elements to represent the calculator buttons. Is there a better way to organise this? If not, can you explain your reasoning for organising this section of code in this way?

I am not a Javascript developer so these are open questions, I want to get an understanding of your decision making process.

**Comment by marvy896** [comment]
This is because the project is small and kind of complicated, separating the classes will make it more ambiguous and wont be understood easily.
so I just want to keep it simple for now, we could do that later when i understand more about classes.

Thanks.
